# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12eSzPkXqWACQNvIM0iJs3OirZE14T5YC
"""



!pip install textblob nltk

import pandas as pd
import matplotlib.pyplot as plt
from textblob import TextBlob
import nltk
from nltk.corpus import stopwords
import re
from google.colab import files
from collections import Counter

nltk.download('stopwords')
stop_words = set(stopwords.words('english'))

uploaded = files.upload()
df = pd.read_csv("Reviews.csv")

def clean_text(text):
    text = str(text).lower()
    text = re.sub(r'[^a-z\s]', '', text)
    words = [w for w in text.split() if w not in stop_words]
    return " ".join(words)

df["Cleaned"] = df["Text"].apply(clean_text)

def get_sentiment(text):
    polarity = TextBlob(text).sentiment.polarity
    if polarity > 0:
        return "Positive"
    elif polarity < 0:
        return "Negative"
    else:
        return "Neutral"

df["Sentiment"] = df["Cleaned"].apply(get_sentiment)

plt.figure(figsize=(6,4))
df["Sentiment"].value_counts().plot(kind="bar", color=["green","red","blue"])
plt.title("Distribution of Sentiments")
plt.show()

if "ProductId" in df.columns:
    avg_sent = df.groupby("ProductId")["Sentiment"].apply(lambda x: (x=="Positive").mean())
    avg_sent.head(10).plot(kind="bar")
    plt.title("Average Positive Sentiment by Product")
    plt.show()

positive_words = " ".join(df[df["Sentiment"]=="Positive"]["Cleaned"]).split()
negative_words = " ".join(df[df["Sentiment"]=="Negative"]["Cleaned"]).split()

print("Most common positive words:", Counter(positive_words).most_common(10))
print("Most common negative words:", Counter(negative_words).most_common(10))