# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13huYGnxQmn3nZxYem3tLyJ2Q18tPN4TW
"""



"""!pip install yfinance

import yfinance as yf
"""

# Step 1: Install required libraries (only run once per session)
!pip install yfinance mplfinance

# Step 2: Import libraries
import yfinance as yf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import mplfinance as mpf

# Step 3: Let user input stock symbol and date range
symbol = input("Enter stock symbol (e.g. AAPL, MSFT, TSLA): ")
start_date = input("Enter start date (YYYY-MM-DD): ")
end_date = input("Enter end date (YYYY-MM-DD): ")

# Step 4: Download stock data
data = yf.download(symbol, start=start_date, end=end_date)

# Flatten the multi-level column index
data.columns = ['_'.join(col).strip() for col in data.columns.values]

# Step 5: Calculate moving averages (20-day and 50-day)
data["MA20"] = data["Price_Close"].rolling(window=20).mean()
data["MA50"] = data["Price_Close"].rolling(window=50).mean()

# Step 6: Identify buy/sell signals
data["Signal"] = 0
data["Signal"] = np.where(data["MA20"] > data["MA50"], 1, -1)
# Access the correct 'Close' column using the multi-level index
data["Buy_Signal"] = np.where((data["Signal"] == 1) & (data["Signal"].shift(1) == -1), data["Price_Close"], np.nan)
data["Sell_Signal"] = np.where((data["Signal"] == -1) & (data["Signal"].shift(1) == 1), data["Price_Close"], np.nan)


# Step 7: Show candlestick chart with moving averages
mpf.plot(
    data,
    type='candle',
    volume=True,
    mav=(20,50),
    title=f"{symbol} Stock Price with MA20 & MA50",
    style='yahoo'
)

# Step 8: Plot buy/sell signals
plt.figure(figsize=(12,6))
plt.plot(data["Price_Close"], label="Close Price", alpha=0.5)
plt.plot(data["MA20"], label="20-day MA")
plt.plot(data["MA50"], label="50-day MA")
plt.scatter(data.index, data["Buy_Signal"], label="Buy Signal", marker="^", color="green")
plt.scatter(data.index, data["Sell_Signal"], label="Sell Signal", marker="v", color="red")
plt.legend()
plt.title(f"{symbol} Buy/Sell Signals")
plt.show()

# Step 9: Calculate key statistics
returns = data["Price_Close"].pct_change().dropna()
volatility = returns.std() * np.sqrt(252)   # annual volatility
cumulative_return = (1 + returns).prod() - 1
sharpe_ratio = returns.mean() / returns.std() * np.sqrt(252)

print("\n📊 Key Statistics:")
print(f"Annual Volatility: {volatility:.2f}")
print(f"Cumulative Return: {cumulative_return:.2%}")
print(f"Sharpe Ratio: {sharpe_ratio:.2f}")